export const SHAPE_DATA = {
            gifts: [
                { id: "A", name: "Administração", desc: "Capacidade de planejar, organizar e executar metas com eficiência." },
                { id: "B", name: "Apostolado", desc: "Visão pioneira para abrir novas frentes, plantar igrejas e liderar." },
                { id: "C", name: "Artesanato", desc: "Capacidade de elaborar criativamente e/ou construir itens." },
                { id: "D", name: "Comunicação Criativa", desc: "Expressar a verdade de Deus através de várias formas de arte." },
                { id: "E", name: "Discernimento", desc: "Distinguir entre a verdade e o erro, o bem e o mal." },
                { id: "F", name: "Encorajamento", desc: "Apresentar a verdade de modo a fortalecer e consolar." },
                { id: "G", name: "Evangelismo", desc: "Comunicar de maneira eficaz o evangelho aos descrentes." },
                { id: "H", name: "Fé", desc: "Agir à luz das promessas de Deus com confiança." },
                { id: "I", name: "Contribuição", desc: "Contribuir com dinheiro e recursos para a obra com alegria." },
                { id: "J", name: "Serviço", desc: "Realizar tarefas práticas e necessárias que apoiam os outros." },
                { id: "L", name: "Hospitalidade", desc: "Cuidar de pessoas, providenciando comunhão, comida e abrigo." },
                { id: "M", name: "Intercessão", desc: "Orar regularmente por outras pessoas, vendo resultados." },
                { id: "N", name: "Conhecimento", desc: "Trazer a verdade ao Corpo pelo discernimento bíblico." },
                { id: "O", name: "Liderança", desc: "Estabelecer uma visão, motivar e direcionar pessoas." },
                { id: "P", name: "Misericórdia", desc: "Ajudar com alegria e forma prática aqueles que sofrem." },
                { id: "Q", name: "Profecia", desc: "Revelar a verdade de Deus e proclamá-la de forma apropriada." },
                { id: "R", name: "Pastorado", desc: "Nutrir, cuidar de pessoas e guiá-las à maturidade." },
                { id: "S", name: "Ensino", desc: "Entender, explicar claramente e aplicar a Palavra de Deus." },
                { id: "T", name: "Sabedoria", desc: "Aplicar verdades espirituais que suprem necessidades." }
            ],
            giftQuestions: [
                { id: "D001", text: "Gosto de organizar pessoas, tarefas e eventos.", domId: "A" },
                { id: "D002", text: "Gostaria de iniciar igrejas em lugares onde elas não existam.", domId: "B" },
                { id: "D003", text: "Gosto de trabalhar criativamente com madeira, tecido, tinta, metal, vidro ou outros materiais.", domId: "C" },
                { id: "D004", text: "Gosto de desafiar a perspectiva que as pessoas têm de Deus por meio de variadas formas de arte.", domId: "D" },
                { id: "D005", text: "Posso distinguir com facilidade entre verdade e erro espiritual, entre o bem e o mal.", domId: "E" },
                { id: "D006", text: "Normalmente reconheço o potencial das pessoas.", domId: "F" },
                { id: "D007", text: "Comunico o evangelho com clareza e de modo eficaz.", domId: "G" },
                { id: "D008", text: "Acho natural e fácil confiar em Deus para responder às minhas orações.", domId: "H" },
                { id: "D009", text: "Contribuo liberalmente e com alegria para pessoas com necessidades financeiras ou para projetos que requerem recursos.", domId: "I" },
                { id: "D010", text: "Gosto de trabalhar na retaguarda apoiando a tarefa de outras pessoas.", domId: "J" },
                { id: "D011", text: "Encaro meu lar como lugar de ministração às pessoas necessitadas.", domId: "L" },
                { id: "D012", text: "Recebo pedidos de oração de outras pessoas e oro por eles regularmente.", domId: "M" },
                { id: "D013", text: "As pessoas pedem a minha opinião sobre uma passagem ou verdade bíblica.", domId: "N" },
                { id: "D014", text: "Consigo motivar pessoas a atingirem um alvo.", domId: "O" },
                { id: "D015", text: "Identifico-me com as pessoas que estão sofrendo, e desejo ajudá-las no processo de restauração.", domId: "P" },
                { id: "D016", text: "Posso falar de maneira a criar convicção e gerar mudança nas vidas dos outros.", domId: "Q" },
                { id: "D017", text: "Gosto de investir tempo nutrindo e cuidando das pessoas.", domId: "R" },
                { id: "D018", text: "Consigo comunicar a Palavra Deus de modo eficaz.", domId: "S" },
                { id: "D019", text: "Freqüentemente as pessoas me procuram para conselho sobre assuntos espirituais ou pessoais.", domId: "T" },
                { id: "D020", text: "Sou cuidadoso, completo e habilitado em administrar detalhes.", domId: "A" },
                { id: "D021", text: "A idéia de servir em outro país ou comunidade é muito interessante para mim.", domId: "B" },
                { id: "D022", text: "Tenho habilidade em trabalhar com vários tipos de ferramentas.", domId: "C" },
                { id: "D023", text: "Gosto de desenvolver e utilizar minhas habilidades artísticas (arte, drama, música, foto, etc).", domId: "D" },
                { id: "D024", text: "Freqüentemente posso discernir o caráter de uma pessoa baseado apenas nas primeiras impressões.", domId: "E" },
                { id: "D025", text: "Gosto de encorajar e fortalecer aqueles que estão abatidos.", domId: "F" },
                { id: "D026", text: "Procuro regularmente oportunidades de construir relacionamentos íntegros com não-crentes.", domId: "G" },
                { id: "D027", text: "Tenho confiança na provisão e ajuda contínua de Deus, mesmo em tempos difíceis.", domId: "H" },
                { id: "D028", text: "Contribuo com mais que o dízimo para que o trabalho do reino seja realizado.", domId: "I" },
                { id: "D029", text: "Gosto de tarefas rotineiras que apóiem o ministério.", domId: "J" },
                { id: "D030", text: "Gosto de conhecer pessoas novas e de ajudá-las a se sentirem bem-vindas.", domId: "L" },
                { id: "D031", text: "Gosto de passar longos períodos em oração, e recebo direção de Deus quanto ao objeto da intercessão.", domId: "M" },
                { id: "D032", text: "Recebo informações do Espírito que não adquiri por meios naturais.", domId: "N" },
                { id: "D033", text: "Posso influenciar pessoas e motivá-las a alcançarem uma visão.", domId: "O" },
                { id: "D034", text: "Consigo apoiar pacientemente aqueles que atravessam experiências dolorosas enquanto tentam normalizar suas vidas.", domId: "P" },
                { id: "D035", text: "Sinto-me responsável por confrontar as pessoas com a verdade.", domId: "Q" },
                { id: "D036", text: "Tenho compaixão pelos crentes que vacilam na fé e tendo a protegê-los.", domId: "R" },
                { id: "D037", text: "Posso investir tempo estudando, sabendo que a apresentação da verdade fará diferença na vida das pessoas.", domId: "S" },
                { id: "D038", text: "Freqüentemente encontro soluções simples e práticas em meio a conflito ou confusão.", domId: "T" },
                { id: "D039", text: "Sei identificar os alvos e desenvolver estratégias para alcançá-los.", domId: "A" },
                { id: "D040", text: "Estou disposto a ter um papel ativo no começo de uma nova igreja.", domId: "B" },
                { id: "D041", text: "Gosto de preparar coisas que serão usadas no ministério.", domId: "C" },
                { id: "D042", text: "Ajudo pessoas, por meio de expressão artística, a entenderem melhor a si mesmas, seus relacionamentos e a Deus.", domId: "D" },
                { id: "D043", text: "Percebo falsidade ou engano antes que seja evidente para outras pessoas.", domId: "E" },
                { id: "D044", text: "Estimulo a esperança nos outros, direcionando-os às promessas de Deus.", domId: "F" },
                { id: "D045", text: "Tenho maneiras de adaptar o evangelho para que seja relevante às necessidades da pessoa.", domId: "G" },
                { id: "D046", text: "Creio que Deus me ajudará a realizar grandes coisas.", domId: "H" },
                { id: "D047", text: "Administro bem minhas finanças para contribuir mais.", domId: "I" },
                { id: "D048", text: "Voluntariamente assumo tarefas “complicadas” na igreja para suprir as necessidades dos outros.", domId: "J" },
                { id: "D049", text: "Acredito verdadeiramente que o Senhor me enviar desconhecidos para que eu os apresente a outras pessoas, ou seja, sou um elo entre pessoas que necessitam umas das outras.", domId: "L" },
                { id: "D050", text: "Sou consciente da ministração aos outros enquanto oro.", domId: "M" },
                { id: "D051", text: "Sou comprometido e disponho de tempo para leitura e estudo das Escrituras, a fim de entender melhor e com precisão as verdades bíblicas.", domId: "N" },
                { id: "D052", text: "Sei ajustar meu estilo de liderança para que outros cresçam, dando o melhor de si.", domId: "O" },
                { id: "D053", text: "Gosto de ajudar as pessoas que são consideradas inúteis ou sem esperança (casos perdidos).", domId: "P" },
                { id: "D054", text: "Contesto ousadamente as tendências culturais, os ensinos ou eventos que contradizem os princípios bíblicos.", domId: "Q" },
                { id: "D055", text: "Gosto de ajudar a pessoa como um todo, relacional, emocional, espiritualmente, etc.", domId: "R" },
                { id: "D056", text: "Presto muita atenção às palavras, frases e explicações das pessoas que ensinam.", domId: "S" },
                { id: "D057", text: "Tenho facilidade de selecionar o modo de agir mais eficaz dentre várias alternativas.", domId: "T" },
                { id: "D058", text: "Posso identificar e usar os recursos necessários para realizar eficientemente uma tarefa.", domId: "A" },
                { id: "D059", text: "Tenho facilidade em me adaptar à culturas e ambientes diferentes.", domId: "B" },
                { id: "D060", text: "Posso visualizar como algo deverá ser construído antes de fazê-lo.", domId: "C" },
                { id: "D061", text: "Gosto de encontrar maneiras novas e interessantes para comunicar a verdade de Deus.", domId: "D" },
                { id: "D062", text: "Percebo as coisas certas ou erradas nas diversas situações.", domId: "E" },
                { id: "D063", text: "Tento encorajar as pessoas que precisam dar passos ousados na sua fé, família ou vida.", domId: "F" },
                { id: "D064", text: "Convido descrentes a aceitarem Cristo como Salvador.", domId: "G" },
                { id: "D065", text: "Confio em Deus nas circunstâncias onde o sucesso não pode ser garantido somente pelo esforço humano.", domId: "H" },
                { id: "D066", text: "Quero controlar meu estilo de vida para que possa contribuir com um percentual maior da minha renda.", domId: "I" },
                { id: "D067", text: "Vejo um significado espiritual em realizar coisas práticas.", domId: "J" },
                { id: "D068", text: "Gosto de criar um ambiente onde as pessoas não se sintam sozinhas.", domId: "L" },
                { id: "D069", text: "Oro com confiança sabendo que Deus age em resposta às orações.", domId: "M" },
                { id: "D070", text: "Tenho discernimento ou simplesmente sei que certas coisas são verdadeiras.", domId: "N" },
                { id: "D071", text: "Sei estabelecer alvos e organizar pessoas e recursos para alcançá-los de forma eficiente.", domId: "O" },
                { id: "D072", text: "Tenho grande compaixão pelas pessoas que sofrem.", domId: "P" },
                { id: "D073", text: "Vejo a maioria das ações como certas ou erradas, e sinto-me na obrigação de corrigir as erradas.", domId: "Q" },
                { id: "D074", text: "Posso proporcionar às pessoas apoio e atenção a longo prazo.", domId: "R" },
                { id: "D075", text: "Gosto de estudar a Bíblia sistematicamente.", domId: "S" },
                { id: "D076", text: "Posso antecipar prováveis conseqüências da ação de um indivíduo ou de um grupo.", domId: "T" },
                { id: "D077", text: "Gosto de ajudar organizações ou grupos a se tornar mais eficientes.", domId: "A" },
                { id: "D078", text: "Sei me relacionar com outras pessoas respeitando as diferenças culturais.", domId: "B" },
                { id: "D079", text: "Honro a Deus com minhas habilidades artesanais.", domId: "C" },
                { id: "D080", text: "Utilizo várias expressões artísticas para comunicar a verdade de Deus.", domId: "D" },
                { id: "D081", text: "Recebo confirmação de outras pessoas quanto à confiança em meu discernimento ou percepção.", domId: "E" },
                { id: "D082", text: "Fortaleço aqueles que estão vacilando na fé.", domId: "F" },
                { id: "D083", text: "Falo abertamente que sou crente e gosto que as pessoas perguntem acerca de minha fé.", domId: "G" },
                { id: "D084", text: "Diariamente tenho plena certeza da presença e ação de Deus em minha vida.", domId: "H" },
                { id: "D085", text: "Fico contente em saber que minha contribuição financeira é significativa na vida e no ministério do povo de Deus.", domId: "I" },
                { id: "D086", text: "Gosto de achar tarefas pequenas para fazer, e freqüentemente as faço sem ninguém pedir.", domId: "J" },
                { id: "D087", text: "Gosto de receber pessoas em minha casa.", domId: "L" },
                { id: "D088", text: "Quando sei de alguma necessidade, sinto-me constrangido a orar.", domId: "M" },
                { id: "D089", text: "Às vezes conheço algo sobre outras pessoas, sem saber exatamente como obtive tal informação.", domId: "N" },
                { id: "D090", text: "Estimulo outras pessoas a superarem seus limites.", domId: "O" },
                { id: "D091", text: "Posso enxergar além das deficiências e problemas de uma pessoa, e ver uma vida com a qual Deus se importa.", domId: "P" },
                { id: "D092", text: "Gosto de pessoas honestas e que falam a verdade.", domId: "Q" },
                { id: "D093", text: "Gosto de dar direção e apoio prático a um grupo pequeno.", domId: "R" },
                { id: "D094", text: "Sei comunicar as Escrituras de forma que os ouvintes estejam motivados a estudar e aprender mais.", domId: "S" },
                { id: "D095", text: "Dou conselhos práticos capazes de ajudar as pessoas que se encontram em situações difíceis.", domId: "T" },
                { id: "D096", text: "Gosto de aprender como as organizações funcionam.", domId: "A" },
                { id: "D097", text: "Gosto de iniciar novos empreendimentos.", domId: "B" },
                { id: "D098", text: "Tenho jeito para trabalhar com as mãos e gosto de fazer isso.", domId: "C" },
                { id: "D099", text: "Sou criativo e tenho imaginação.", domId: "D" },
                { id: "D100", text: "Sei identificar pregações, ensino ou comunicação que não estão de acordo com a verdade bíblica.", domId: "E" },
                { id: "D101", text: "Gosto de motivar as pessoas a dar passos de crescimento espiritual.", domId: "F" },
                { id: "D102", text: "Digo aberta e claramente o que Cristo fez por mim.", domId: "G" },
                { id: "D103", text: "Normalmente desafio às pessoas a confiarem em Deus.", domId: "H" },
                { id: "D104", text: "Contribuo liberalmente devido ao meu compromisso como mordomo de Cristo.", domId: "I" },
                { id: "D105", text: "Sinto-me bem sendo colaborador e ajudando as pessoas a fazerem suas tarefas de forma eficiente.", domId: "J" },
                { id: "D106", text: "Faço o que for possível para que as pessoas se sintam parte do grupo.", domId: "L" },
                { id: "D107", text: "Sinto-me honrado quando alguém me pede oração.", domId: "M" },
                { id: "D108", text: "Enquanto leio ou estudo a Bíblia, descubro verdades bíblicas importantes que beneficiam outros no corpo de Cristo.", domId: "N" },
                { id: "D109", text: "Sei expor uma visão de modo que as pessoas sintam-se motivadas a participar do empreendimento.", domId: "O" },
                { id: "D110", text: "Gosto de trazer esperança e alegria às pessoas que se encontram em situações difíceis.", domId: "P" },
                { id: "D111", text: "Proclamarei a verdade de Deus mesmo em lugares onde ela não for popular ou aceita.", domId: "Q" },
                { id: "D112", text: "Consigo ajudar os desviados a voltarem para Cristo.", domId: "R" },
                { id: "D113", text: "Sei passar às pessoas informações e habilidades num nível que seja fácil de compreender e aplicar.", domId: "S" },
                { id: "D114", text: "Posso aplicar verdades bíblicas de modo que outros achem prático e eficaz.", domId: "T" },
                { id: "D115", text: "Consigo conceber um evento a ser realizado, antecipando os problemas e imaginando formas de resolvê-los.", domId: "A" },
                { id: "D116", text: "Posso administrar e supervisionar vários ministérios da igreja.", domId: "B" },
                { id: "D117", text: "Posso planejar e construir coisas que ajudam a igreja.", domId: "C" },
                { id: "D118", text: "Regularmente preciso estar a sós para refletir e desenvolver minha imaginação.", domId: "D" },
                { id: "D119", text: "Posso perceber quando poderes demoníacos estão agindo em uma situação ou pessoa.", domId: "E" },
                { id: "D120", text: "Posso desafiar ou repreender as pessoas para estimular o crescimento espiritual delas.", domId: "F" },
                { id: "D121", text: "Procuro oportunidades para conversar com descrentes sobre coisas espirituais.", domId: "G" },
                { id: "D122", text: "Posso ir em frente, apesar da oposição ou falta de apoio, quando percebo a bênção de Deus sobre um empreendimento.", domId: "H" },
                { id: "D123", text: "Acredito que o Senhor tem me dado recursos em abundância para que eu possa contribuir mais para a obra do reino.", domId: "I" },
                { id: "D124", text: "Estou disposto a utilizar meus talentos (naturais ou adquiridos) para ajudar conforme for necessário, fazendo isso com muita alegria.", domId: "J" },
                { id: "D125", text: "Consigo levar as pessoas a se sentirem à vontade em ambientes desconhecidos.", domId: "L" },
                { id: "D126", text: "Freqüentemente vejo resultados específicos como respostas diretas das minhas orações.", domId: "M" },
                { id: "D127", text: "Compartilho confiantemente meu conhecimento e minhas percepções com os outros.", domId: "N" },
                { id: "D128", text: "Enxergo para onde devemos ir, e sei planejar os passos para chegarmos lá.", domId: "O" },
                { id: "D129", text: "Gosto de fazer algo prático por pessoas necessitadas.", domId: "P" },
                { id: "D130", text: "Quando percebo uma situação de pecado, sinto-me compelido a denunciá-la e admoestar as pessoas envolvidas ao arrependimento.", domId: "Q" },
                { id: "D131", text: "Gosto de nutrir as pessoas em processo de crescimento espiritual, com paciência, mas com firmeza.", domId: "R" },
                { id: "D132", text: "Gosto de dar explicação às pessoas sobre assuntos que possam fazê-las crescer pessoal e espiritualmente.", domId: "S" },
                { id: "D133", text: "Penso em soluções de problemas que normalmente as pessoas não pensam.", domId: "T" }
            ],
            personality: {
                eixo_org: {
                    title: "Como me organizo (Formal x Informal)",
                    items: [
                        { id: "O1", esq: "Ser espontâneo", dir: "Seguir um plano fixo", ctx: "Nas férias, eu preferiria..." },
                        { id: "O2", esq: "Gerais", dir: "Específicas", ctx: "Eu preferiria traçar diretrizes..." },
                        { id: "O3", esq: "Em aberto", dir: "Resolver logo", ctx: "Eu preferiria deixar opções..." },
                        { id: "O4", esq: "Variedade", dir: "Rotina", ctx: "Eu preferiria projetos que tivessem..." },
                        { id: "O5", esq: "Improvisar", dir: "Seguir um plano", ctx: "Eu gostaria de..." },
                        { id: "O6", esq: "Chata", dir: "Segura (posso descansar)", ctx: "Eu acharia a rotina..." },
                        { id: "O7", esq: "Resolvendo coisas ao longo do projeto", dir: "Seguindo um plano", ctx: "Eu realizaria melhor as tarefas quando..." }
                    ]
                },
                eixo_mot: {
                    title: "Como me motivo (Tarefas x Pessoas)",
                    items: [
                        { id: "M1", esq: "Fazendo algo para as pessoas", dir: "Estando com as pessoas", ctx: "Eu me sentiria melhor..." },
                        { id: "M2", esq: "Focalizar no alvo", dir: "Focalizar nos relacionamentos", ctx: "Quando estivesse realizando uma tarefa, eu gostaria de..." },
                        { id: "M3", esq: "O avanço de uma causa", dir: "O sentido de comunidade", ctx: "Minha empolgação seria com..." },
                        { id: "M4", esq: "Terminasse uma tarefa", dir: "Construísse um relacionamento", ctx: "Eu sentiria que realizei algo quando..." },
                        { id: "M5", esq: "Pontualmente", dir: "Quando todos estiverem presentes", ctx: "É mais importante começar..." },
                        { id: "M6", esq: "Em cumprir um prazo", dir: "Em manter a equipe", ctx: "Eu estaria mais preocupado..." },
                        { id: "M7", esq: "A ação", dir: "A comunicação", ctx: "Eu valorizaria mais..." }
                    ]
                }
            },
            abilities: [
                {
                    area: "Comunicação e ensino",
                    items: ["Falar em público com desenvoltura", "Escrever textos, roteiros ou estudos", "Explicar assuntos complexos de forma simples", "Traduzir/interpretar idiomas"]
                },
                {
                    area: "Música e artes",
                    items: ["Tocar um instrumento", "Cantar ou liderar louvor", "Compor ou arranjar música", "Desenho, pintura, design gráfico ou fotografia", "Dança, teatro ou artes cênicas", "Produção de vídeo/edição"]
                },
                {
                    area: "Tecnologia e produção",
                    items: ["Programação/desenvolvimento de sistemas", "Operação de som, luz ou projeção", "Edição/produção audiovisual", "Redes sociais e marketing digital", "Suporte técnico e informática"]
                },
                {
                    area: "Organização e gestão",
                    items: ["Planejamento financeiro e orçamento", "Organização de eventos", "Gestão de pessoas/equipes", "Planejamento estratégico", "Controle de dados e processos"]
                },
                {
                    area: "Trabalho manual e construção",
                    items: ["Marcenaria, elétrica, hidráulica ou reparos gerais", "Culinária e produção de alimentos em escala", "Costura ou artesanato", "Jardinagem e manutenção de espaços"]
                },
                {
                    area: "Cuidado e relacionamento",
                    items: ["Aconselhamento e escuta ativa", "Cuidado com crianças", "Cuidado com idosos ou enfermos", "Recepção e atendimento ao público", "Mediação de conflitos"]
                },
                {
                    area: "Saúde e bem-estar",
                    items: ["Formação ou experiência na área da saúde", "Educação física e esportes", "Nutrição"]
                }
            ],
            heart: [
                "Em que direção meus sonhos e desejos estão me levando? O que eu realmente quero fazer para Deus?",
                "Quem eu sinto que posso influenciar mais profundamente para Deus? A que faixa etária ou grupo sinto que devo ministrar?",
                "Que necessidades eu amo suprir na vida de outra pessoa? Que lições aprendi que poderia transmitir a outras pessoas?",
                "Que causa ou assunto faz meu coração bater mais rápido? Onde eu poderia causar o maior impacto por Deus?",
                "Qual é o meu maior sonho para o Reino de Deus?"
            ],
            experiences: [
                { id: "exp1", label: "Formação/experiência profissional" },
                { id: "exp2", label: "Experiência prévia em ministérios (dentro ou fora da igreja)" },
                { id: "exp3", label: "Experiências difíceis que Deus usou para me preparar (opcional)" },
                { id: "exp4", label: "Disponibilidade (dias/horários) [Ex: Domingo manhã, dias de semana...]" }
            ]
        };
;
