import { KpiTemplate } from '@/domain/kpi';

export const SYSTEM_KPI_TEMPLATES: KpiTemplate[] = [
  {
    id: 'celulas',
    name: 'Número de Células',
    description: 'Total de células cadastradas no sistema',
    iconName: 'Users',
    category: 'gc',
    defaultDataSource: {
      type: 'collection_count',
      collectionName: 'cells',
    },
    isSystemDefault: true,
  },
  {
    id: 'frequencia_culto_dom_0730',
    name: 'Frequência Dom - 07:30',
    description: 'Média de público no culto de Domingo 07:30',
    iconName: 'CheckSquare',
    category: 'culto',
    defaultDataSource: {
      type: 'attendance_avg',
      horario: 'Domingo - 07:30',
    },
    isSystemDefault: true,
  },
  {
    id: 'frequencia_culto_dom_1015',
    name: 'Frequência Dom - 10:15',
    description: 'Média de público no culto de Domingo 10:15',
    iconName: 'CheckSquare',
    category: 'culto',
    defaultDataSource: {
      type: 'attendance_avg',
      horario: 'Domingo - 10:15',
    },
    isSystemDefault: true,
  },
  {
    id: 'frequencia_culto_dom_1730',
    name: 'Frequência Dom - 17:30',
    description: 'Média de público no culto de Domingo 17:30',
    iconName: 'CheckSquare',
    category: 'culto',
    defaultDataSource: {
      type: 'attendance_avg',
      horario: 'Domingo - 17:30',
    },
    isSystemDefault: true,
  },
  {
    id: 'frequencia_culto_dom_1930',
    name: 'Frequência Dom - 19:30',
    description: 'Média de público no culto de Domingo 19:30',
    iconName: 'CheckSquare',
    category: 'culto',
    defaultDataSource: {
      type: 'attendance_avg',
      horario: 'Domingo - 19:30',
    },
    isSystemDefault: true,
  },
  {
    id: 'frequencia_culto_qui_2000',
    name: 'Frequência Qui - 20:00',
    description: 'Média de público no culto de Quinta 20:00',
    iconName: 'CheckSquare',
    category: 'culto',
    defaultDataSource: {
      type: 'attendance_avg',
      horario: 'Quinta - 20:00',
    },
    isSystemDefault: true,
  },
  {
    id: 'frequencia_culto_evento',
    name: 'Frequência Eventos',
    description: 'Média de público em eventos especiais',
    iconName: 'CheckSquare',
    category: 'culto',
    defaultDataSource: {
      type: 'attendance_avg',
      horario: 'Evento',
    },
    isSystemDefault: true,
  },
  {
    id: 'conversoes',
    name: 'Conversões',
    description: 'Total de conversões relatadas nos relatórios',
    iconName: 'UserPlus',
    category: 'crescimento',
    defaultDataSource: {
      type: 'field_sum',
      collectionName: 'attendance_reports',
      field: 'conversoes',
    },
    isSystemDefault: true,
  },
  {
    id: 'batismos',
    name: 'Batismos',
    description: 'Pessoas batizadas ou com curso de batismo concluído',
    iconName: 'Crosshair',
    category: 'crescimento',
    defaultDataSource: {
      type: 'user_field',
      field: 'batizado',
      value: 'sim',
      courseName: 'batismo',
    },
    isSystemDefault: true,
  },
  {
    id: 'curso_crescer',
    name: 'Concluíram: Crescer',
    description: 'Alunos aptos/aprovados no curso Crescer',
    iconName: 'GraduationCap',
    category: 'ensino',
    defaultDataSource: {
      type: 'course_completion',
      courseName: 'crescer',
    },
    isSystemDefault: true,
  },
  {
    id: 'curso_cuidar',
    name: 'Concluíram: Cuidar',
    description: 'Alunos aptos/aprovados no curso Cuidar',
    iconName: 'GraduationCap',
    category: 'ensino',
    defaultDataSource: {
      type: 'course_completion',
      courseName: 'cuidar',
    },
    isSystemDefault: true,
  },
  {
    id: 'curso_discipular',
    name: 'Concluíram: Discipular',
    description: 'Alunos aptos/aprovados no curso Discipular',
    iconName: 'GraduationCap',
    category: 'ensino',
    defaultDataSource: {
      type: 'course_completion',
      courseName: 'discipular',
    },
    isSystemDefault: true,
  },
  {
    id: 'curso_apoiar',
    name: 'Concluíram: Apoiar',
    description: 'Alunos aptos/aprovados no curso Apoiar',
    iconName: 'GraduationCap',
    category: 'ensino',
    defaultDataSource: {
      type: 'course_completion',
      courseName: 'apoiar',
    },
    isSystemDefault: true,
  },
  {
    id: 'curso_enviar',
    name: 'Concluíram: Enviar',
    description: 'Alunos aptos/aprovados no curso Enviar',
    iconName: 'GraduationCap',
    category: 'ensino',
    defaultDataSource: {
      type: 'course_completion',
      courseName: 'enviar',
    },
    isSystemDefault: true,
  },
  {
    id: 'novos_lideres',
    name: 'Formação de Novos Líderes',
    description: 'Membros em função ou status de liderança',
    iconName: 'GraduationCap',
    category: 'lideranca',
    defaultDataSource: {
      type: 'user_role',
      roles: ['lider_treinamento', 'lider_gc', 'lider_area', 'lider_rede', 'pastor', 'pastor_senior', 'admin'],
    },
    isSystemDefault: true,
  },
];
